name: Coverage
on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    
    - name: Install dependencies
      run: npm install
      
    - name: Run tests with coverage
      run: npm run coverage
      
    - uses: qltysh/qlty-action/coverage@main
      with:
        coverage-token: {{secrets.QLTY_COVERAGE_TOKEN}}
        files: coverage/lcov.info